final baseUrl = 'https://ferasalhallak.online/api/auth/login';
final permissionUrl = 'https://ferasalhallak.online/api/auth/me';
final allCurrencyUrl = 'https://ferasalhallak.online/api/currencyPrices/';
final currencyUpdateUrl = 'https://ferasalhallak.online/api/currencyPrices';
final addPost = 'https://ferasalhallak.online/api/posts';
final allPost = 'https://ferasalhallak.online/api/posts';
final allCompanyPost = 'https://ferasalhallak.online/api/posts/company/';
final chartUrl = 'https://ferasalhallak.online/api/currencyChart?city_id=';
final followUrl = 'https://ferasalhallak.online/api/followCompany?company_id=';
